name: release

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
env:
  PROJECT_NAME: 'zfs-tool'
  PROJECT_PATH: 'zfs-tool/zfs-tool.csproj'
  PROJECT_OUTPUT_PATH: ${{ github.workspace }}/output/
  DOTNET_VERSION: '6.0.405'
  DOTNET_FRAMEWORK: 'net6.0'
jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: [
          'linux',
          'linux-musl-x64',
          'linux-arm',
          'linux-arm64',
          'windows',
          'macOS',
          'macOS-arm'
        ]
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: linux-musl-x64
            os: ubuntu-latest
            target: linux-musl-x64 # for docker
          - kind: linux-arm
            os: ubuntu-latest
            target: linux-arm
          - kind: linux-musl-arm
            os: ubuntu-latest
            target: linux-musl-arm
          - kind: linux-arm64
            os: ubuntu-latest
            target: linux-arm64
          - kind: linux-musl-arm64
            os: ubuntu-latest
            target: linux-musl-arm64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
          - kind: macOS-arm
            os: macos-latest
            target: osx-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: "https://nuget.pkg.github.com/sandreas/index.json"
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Get version
        id: version
        uses: battila7/get-version-action@v2

      - name: Build
        id: build
        shell: bash
        run: |
          release_name="${{ env.PROJECT_NAME }}-${{ steps.version.outputs.version-without-v }}-${{ matrix.target }}"
          release_notes="$(sed 's/%/%25/g;s/\r/%0D/g;' ${{ env.PROJECT_NAME }}/doc/release/release-notes-${{ steps.version.outputs.version }}.md | sed ':a;N;$!ba;s/\n/%0A/g')"
          
          echo "::set-output name=release_notes::$release_notes"
          
          sed -i.bak "s/<TargetFramework>net6.0<\/TargetFramework>/<TargetFramework>${{ env.DOTNET_FRAMEWORK }}<\/TargetFramework>/g" ${{ env.PROJECT_PATH }}
          
          if [ "${{ matrix.target }}" == "osx-arm64" ]; then
            dotnet publish ${{ env.PROJECT_PATH }} --framework ${{ env.DOTNET_FRAMEWORK }} --runtime "${{ matrix.target }}" -c Release -p:EnableCompressionInSingleFile=false -p:PublishSingleFile=true --self-contained true -p:PublishReadyToRun=true -p:PublishTrimmed=true -o "$release_name"
          else 
            dotnet publish ${{ env.PROJECT_PATH }} --framework ${{ env.DOTNET_FRAMEWORK }} --runtime "${{ matrix.target }}" -c Release -p:PublishSingleFile=true --self-contained true -p:PublishReadyToRun=true -p:PublishTrimmed=true -o "$release_name"
          fi
          
          
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            7z a -tzip "${release_name}.zip" "./${release_name}/zfs-tool.exe"
          else
            tar czvf "${release_name}.tar.gz" "$release_name/zfs-tool"
          fi
          rm -r "$release_name"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ env.PROJECT_NAME }}-${{ steps.version.outputs.version-without-v }}-${{ matrix.target }}*"
          body: "${{ steps.build.outputs.release_notes }}"
          prerelease: endsWith(github.ref, 'prerelease')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
